# Generated by Django 5.1.7 on 2025-04-08 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '__first__'),
        ('models', '0003_alter_lm_models_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_name', models.CharField(help_text='평가 벤치마크 이름 (예: MMLU)', max_length=255)),
                ('metrics', models.JSONField(blank=True, help_text="측정 지표 예: {'BLEU': 0.75, 'ROUGE': 0.82, 'ACC': 0.90}", null=True)),
                ('dataset_version', models.CharField(blank=True, help_text='데이터셋 버전', max_length=100, null=True)),
                ('tag', models.CharField(max_length=512)),
                ('dataset_name', models.ForeignKey(help_text='평가 벤치마크 이름 (예: MMLU)', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='datasets.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(blank=True, help_text="측정 지표 예: {'BLEU': 0.75, 'ROUGE': 0.82, 'ACC': 0.90}", null=True)),
                ('dataset_version', models.CharField(blank=True, help_text='데이터셋 버전', max_length=100, null=True)),
                ('date_evaluated', models.DateField(blank=True, help_text='평가한 날짜', null=True)),
                ('evaluate_result', models.JSONField(blank=True, help_text='평가 결과 샘플 파일', null=True)),
                ('benchmark_name', models.ForeignKey(help_text='평가 벤치마크 이름 (예: MMLU)', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_dashboard.benchmark')),
                ('llm_model', models.ForeignKey(help_text='평가된 모델', on_delete=django.db.models.deletion.CASCADE, related_name='model_name', to='models.lm_models')),
            ],
        ),
    ]
