# Generated by Django 5.1.7 on 2025-04-09 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_dashboard', '0003_alter_benchmark_benchmark_name'),
        ('models', '0004_alter_lm_models_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkresult',
            name='llm_model',
            field=models.ForeignKey(help_text='평가된 모델', on_delete=django.db.models.deletion.CASCADE, related_name='model_name', to='models.lm_models', unique=True),
        ),
    ]
