# Generated by Django 5.1.7 on 2025-04-09 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_dashboard', '0004_alter_benchmarkresult_llm_model'),
        ('models', '0004_alter_lm_models_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkresult',
            name='llm_model',
            field=models.ForeignKey(help_text='평가된 모델', on_delete=django.db.models.deletion.CASCADE, related_name='model_name', to='models.lm_models'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkresult',
            constraint=models.UniqueConstraint(fields=('llm_model', 'benchmark_name'), name='unique_model_per_benchmark'),
        ),
    ]
