# Generated by Django 5.1.7 on 2025-04-17 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0004_alter_lm_models_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtype', models.CharField(max_length=128)),
                ('server', models.CharField(max_length=128)),
                ('docker_name', models.CharField(max_length=128)),
                ('triton_port', models.CharField(max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.lm_models')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('llm_model', 'playtype'), name='unique_model_per_playground')],
            },
        ),
    ]
