# Generated by Django 5.1.7 on 2025-04-18 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_playground_end_time_playground_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='playground',
            name='gpu_index',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playground',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
