# Generated by Django 5.1.7 on 2025-04-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('task_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(related_name='projects', through='label_studio.Assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data', to='label_studio.project')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='label_studio.project'),
        ),
        migrations.CreateModel(
            name='WorkResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_results', to='label_studio.inputdata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_results', to='label_studio.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='label_studio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['project'], name='label_studi_project_2ab741_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inputdata',
            index=models.Index(fields=['project', 'order'], name='label_studi_project_86748a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('worker', 'project')},
        ),
        migrations.AddIndex(
            model_name='workresult',
            index=models.Index(fields=['input_data'], name='label_studi_input_d_265b46_idx'),
        ),
        migrations.AddIndex(
            model_name='workresult',
            index=models.Index(fields=['project'], name='label_studi_project_32d070_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workresult',
            unique_together={('input_data', 'worker')},
        ),
    ]
