# Generated by Django 5.1.7 on 2025-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_status',
            field=models.CharField(choices=[('in_progress', '작업중'), ('completed', '완료'), ('stopped', '중단')], default='in_progress', max_length=20),
        ),
    ]
