# Generated by Django 5.1.7 on 2025-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_studio', '0002_project_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guideline_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workresult',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
