# Generated by Django 5.1.7 on 2025-04-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lm_models',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lm_models',
            name='subject',
        ),
    ]
