# Generated by Django 5.1.7 on 2025-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_lm_models_content_remove_lm_models_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lm_models',
            name='tag',
            field=models.CharField(max_length=512),
        ),
    ]
