# Generated by Django 5.1.7 on 2025-04-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_lm_models_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lm_models',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
