# Generated by Django 5.1.7 on 2025-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_lm_models_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lm_models',
            name='task_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
